Preguntas_Deporte = {1:'Cuantos campeonatos ganados tiene Michael Jordan',
                     2:'En cuales equipos estuvo Lebron James',
                     3:'Cuantos triples metio Curry',
                     4:'Que equipo gano la ultima NBA',
                     5:'Cual de los siguientes jugadores Agentinos estara en el salon de la fama',
                     6:'Cuantos Mundiales tiene Alemania',
                     7:'A partir de qué temporada se implantó el VAR en LaLiga',
                     8:'Cuantos balones de oro tiene Messi',
                     9:'En que equipo debuto Maradona',
                     10:'Cuantos mundiales tiene Pele',
                     11:'Cuanto mide una cancha de voley de largo',
                     12:'Cuantas copas americas tiene Brasil',
                     13:'Quienes llegaron a la final en el mundial 2010',
                     14:'Quien gano el mundial de voley en 2022',
                     15:'Quien gano la ultima competencia de naatacion en las olimpiadas',
                     16:'Cuál es el tenista con más títulos de la historia',
                     17:'Cuanto duro el partido de tenis mas largo de la historia',
                     18:'Donde se creo el tenis',
                     19:'Cuántos titulos ha ganado Hamilton',
                     20:'Quién ganó 4 mundiales consecutivos en la Fórmula 1'}
Preguntas_Ciencia = {1:'Cuanto es: 2 + 3x10 + 0',
                     2:'Cual es el órgano más grande, visible y pesado del cuerpo',
                     3:'Que organo se encarga del equilibrio',
                     4:'Cual es la molecula del agua',
                     5:'Cuanto es: (1000 + 1214 + 213918) * 0',
                     6:'Que descubrio Nobel',
                     7:'Que descubrio Newton',
                     8:'Cual es la molecula de acido sulfurico',
                     9:'Cual es el primer atomo de la tabla periodica',
                     10:'Cual es la molecula del dioxido de carbono',
                     11:'Cual es la distancia entre la Tierra y la Luna',
                     12:'Cual es el diametro de la tierra',
                     13:'Cual es la formula de Fuerza',
                     14:'Como se llama la primera ley de Newton',
                     15:'Como es la formula de la velocidad',
                     16:'Como se llama la tercera ley de Newton',
                     17:'Que necesitan las plantas para hacer la fotosintesis',
                     18:'Cuanto es: 100+10',
                     19:'Que descubrio Tesla',
                     20:'Que descubrio Einstein'}
Preguntas_Geografia = {1:'Cuantos paises hay en el mundo',
                       2:'Cuantas provincias tiene Argentina',
                       3:'Cual es rio mas extenso del mundo',
                       4:'Cual es el pais mas grande de Europa',
                       5:'Cuantos continentes hay en el mundo',
                       6:'Nombra un pais de Asia',
                       7:'Nombra un pais de America',
                       8:'Nombra un pais de Oceania',
                       9:'Nombra un pais de Europa',
                       10:'Nombra un pais de Africa',
                       11:'Que oceano divide a Europa y Africa',
                       12:'Donde esta la Torre Eiffel',
                       13:'Donde esta La Estatua de la Libertad',
                       14:'Donde esta el Coliseo Romano',
                       15:'En que continentes esta Turquia',
                       16:'En que continente esta Peru',
                       17:'Donde se encuentra El Cristo Redentor',
                       18:'Donde esta el Gran Cañon',
                       19:'Donde esta la Torre de Pizza',
                       20:'Cual es el pais mas chico del mundo'}
Preguntas_Entretenimiento = {1:'Nombra un personaje perteneciente a la familia Simpsons',
                            2:'Cual es la serie mas larga',
                            3:'Cual es la pelicula mas larga',
                            4:'Que pelicula se llevo mas premios',
                            5:'En cual de estas peliculas no actua Robert De Niro',
                            6:'En cual de estas peliculas actua Tom Hanks',
                            7:'Completa la canción:\nMamaaa\nJust killed a man\n......\nNow he is dead',
                            8:'Cuantos hijos tenia Pepe de Casados con hijos',
                            9:'Nombra una pelicula en la qque actue Guillermo Francella',
                            10:'Cuantas peliculas tiene Harry Potter',
                            11:'Cuantas peliculas tiene Star Wars',
                            12:'Como se llama la tercera pelicula de Star Wars',
                            13:'En que año salio la primera pelicula de Los juegos del hambre',
                            14:'Quien hizo de Thomas Shelby',
                            15:'Quien hizo de Thor',
                            16:'Quien dirijio Interestellar',
                            17:'Cuantas peliculas hay de Jurasic Park',
                            18:'En que año salio la primera pelica de Star Wars',
                            19:'Completa la cancion:\nTell me why\nAint nothin but a heartache\n....',
                            20:'Quien protagonizo Forrest Gump'}
Preguntas_Historia = {1:'En que año inicio la Primera Guerra Mundial',
                     2:'Quien descubrio America',
                     3:'Cuando se realizo la Revolucion Industrial',
                     4:'Cuando se realizo la Revolucion Francesa',
                     5:'En que año se creo la primera maquina a vapor',
                     6:'Cuando cayó el muro de Berlín',
                     7:'Cuando se descubrio America',
                     8:'Cuanto duro la primera guerra mundial',
                     9:'Cuando se creo la Constitucion Argentina',
                     10:'Cuando se Independizo USA',
                     11:'Cuando se Independizo Argentina',
                     12:'Cuando empezo el Paleolitico',
                     13:'Como se extinguieron los dinosaurios',
                     14:'Cual fue la primera pandemia del mundo',
                     15:'Como murio Hitler',
                     16:'Quien fue Napoleon Bonaparte',
                     17:'En que periodo fue el Renacimiento',
                     18:'Quien esta en el billete de 100 pesos',
                     19:'Que se festeja el 9 de julio',
                     20:'Quien creo la bandera Argentina'}
Preguntas_Arte = {   1:'Cuál es la obra artística mexica más grande',
                     2:'Cuántas pinturas se conocen de Da Vinci',
                     3:'Quién pintó con cadáveres humanos',
                     4:'Quién es Hokusai',
                     5:'Nombra una obra de Shakespeare',
                     6:'Qué ciudad está plasmada en “La noche estrellada” de Van Gogh',
                     7:'Qué artista hizo un holograma de Alice Cooper',
                     8:'Quien hizo el Martin Fierro',
                     9:'Que parte del cuerpo le faltaba a Van Gogh',
                     10:'Que color de pintura comia Van Gogh',
                     11:'Quien pinto la Mona Lisa',
                     12:'Que color sale de la mezcla de: Azul y Amarillo',
                     13:'Cuantos notas musicales hay',
                     14:'Cuantas sinfonias hizo Bethovenn',
                     15:'Quien hizo Clair de Mune',
                     16:'Quien fue conocido como el rey del Blues',
                     17:'Quien fue conocido como el rey del Pop',
                     18:'Cuales son los colores primarios',
                     19:'Que tipos de colores existen',
                     20:'Quien pinto la ultima cena'}
